name: module3_task3
run-name: module3_task3
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  job1:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      # ... other steps ...

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Authenticate with GitHub
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 1.0.0
          release_name: Release 1.0.0
          body: ${{ steps.txt.outputs.body }}
          commitish: ${{ github.sha }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: module3_task2/awesome-website.zip
          asset_name: awesome-website.zip
          asset_content_type: application/zip
