name: module3_task3
run-name: module3_task3
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  job1:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup module3_task2
        run: sudo ./module3_task2/setup.sh
      - name: Test module3_task2
        run: make test -C module3_task2
      - name: Build module3_task2
        run: make build -C module3_task2
      - name: Package module3_task2
        run: make package -C module3_task2
      - name: Run module3_task2
        run: make run -C module3_task2
      - name: Stop module3_task2
        run: make stop -C module3_task2
      - name: Clean module3_task2
        run: make clean -C module3_task2
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: 1.0.0
          release_name: Release 1.0.0
          body: ${{ steps.txt.outputs.body }}
          commitish: ${{ github.sha }}
          token: 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
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: module3_task2/awesome-website.zip
          asset_name: awesome-website.zip
          asset_content_type: application/zip
          token: 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
