name: module3_task1
run-name: module3_task1
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  job1:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo ./module3_task1/setup.sh
      - run: npm install -g markdownlint-cli
      - run: npm install -g markdown-link-check
      - uses: actions/setup-go@v4
        with:
          go-version: '1.17'
      - run: make test -C module3_task1
      - run: make build -C module3_task1
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29
      - run: make run -C module3_task1
      - run: make stop -C module3_task1
      - run: make clean -C module3_task1
      